// <auto-generated />
using Hyper.Entities.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hyper.Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hyper.Entities.Models.Concrete.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red"
                        },
                        new
                        {
                            Id = 2,
                            Color = "blue"
                        },
                        new
                        {
                            Id = 3,
                            Color = "white"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red"
                        },
                        new
                        {
                            Id = 5,
                            Color = "black"
                        },
                        new
                        {
                            Id = 6,
                            Color = "white"
                        },
                        new
                        {
                            Id = 7,
                            Color = "blue"
                        },
                        new
                        {
                            Id = 8,
                            Color = "black"
                        },
                        new
                        {
                            Id = 9,
                            Color = "cyan"
                        },
                        new
                        {
                            Id = 10,
                            Color = "white"
                        },
                        new
                        {
                            Id = 11,
                            Color = "cyan"
                        },
                        new
                        {
                            Id = 12,
                            Color = "blue"
                        },
                        new
                        {
                            Id = 13,
                            Color = "black"
                        },
                        new
                        {
                            Id = 14,
                            Color = "red"
                        },
                        new
                        {
                            Id = 15,
                            Color = "white"
                        },
                        new
                        {
                            Id = 16,
                            Color = "red"
                        });
                });

            modelBuilder.Entity("Hyper.Entities.Models.Concrete.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red"
                        },
                        new
                        {
                            Id = 2,
                            Color = "yellow"
                        },
                        new
                        {
                            Id = 3,
                            Color = "white"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red"
                        },
                        new
                        {
                            Id = 5,
                            Color = "black"
                        },
                        new
                        {
                            Id = 6,
                            Color = "white"
                        },
                        new
                        {
                            Id = 7,
                            Color = "blue"
                        },
                        new
                        {
                            Id = 8,
                            Color = "yellow"
                        },
                        new
                        {
                            Id = 9,
                            Color = "cyan"
                        },
                        new
                        {
                            Id = 10,
                            Color = "white"
                        },
                        new
                        {
                            Id = 11,
                            Color = "cyan"
                        },
                        new
                        {
                            Id = 12,
                            Color = "blue"
                        },
                        new
                        {
                            Id = 13,
                            Color = "black"
                        },
                        new
                        {
                            Id = 14,
                            Color = "red"
                        },
                        new
                        {
                            Id = 15,
                            Color = "white"
                        },
                        new
                        {
                            Id = 16,
                            Color = "yellow"
                        });
                });

            modelBuilder.Entity("Hyper.Entities.Models.Concrete.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HeadlightsOn")
                        .HasColumnType("bit");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red",
                            HeadlightsOn = true,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Color = "black",
                            HeadlightsOn = false,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 3,
                            Color = "white",
                            HeadlightsOn = false,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 4,
                            Color = "blue",
                            HeadlightsOn = true,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "yellow",
                            HeadlightsOn = true,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 6,
                            Color = "yellow",
                            HeadlightsOn = false,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 7,
                            Color = "blue",
                            HeadlightsOn = false,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 8,
                            Color = "white",
                            HeadlightsOn = false,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 9,
                            Color = "black",
                            HeadlightsOn = true,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 10,
                            Color = "red",
                            HeadlightsOn = false,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 11,
                            Color = "black",
                            HeadlightsOn = true,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 12,
                            Color = "white",
                            HeadlightsOn = true,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 13,
                            Color = "blue",
                            HeadlightsOn = false,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 14,
                            Color = "yellow",
                            HeadlightsOn = true,
                            Wheels = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
